### ISSUE TITLE
爬取长时间历史新闻

### ISSUE THREAD

**Issue by AStupidBear** [DemonDamon/FinnewsHunter#2]
请教一下，比如新浪，只能看到23页，更久的数据浏览器都不显示，更不用说爬。不知道您是怎么解决的？

**Comment by DemonDamon** [comment]
这个没得解决吧，除非去hack？

**Comment by DemonDamon** [comment]
> 请教一下，比如新浪，只能看到23页，更久的数据浏览器都不显示，更不用说爬。不知道您是怎么解决的？

这个应该没法解决，服务端做了限制，爬取前提是有数据respond。
